INSERT INTO category (name) values ('Agriculture');
INSERT INTO category (name) values ('Anthropology');
INSERT INTO category (name) values ('Archaeology');
INSERT INTO category (name) values ('Architecture');
INSERT INTO category (name) values ('Art');
INSERT INTO category (name) values ('Astronomy');
INSERT INTO category (name) values ('Biographies');
INSERT INTO category (name) values ('Biology');
INSERT INTO category (name) values ('Botany');
INSERT INTO category (name) values ('Chemistry');
INSERT INTO category (name) values ('Cinema & show');
INSERT INTO category (name) values ('Computer & IT');
INSERT INTO category (name) values ('Cook');
INSERT INTO category (name) values ('Design & graphic');
INSERT INTO category (name) values ('Ecology & environment');
INSERT INTO category (name) values ('Economy & Management');
INSERT INTO category (name) values ('Education & training');
INSERT INTO category (name) values ('Engineering & Technology');
INSERT INTO category (name) values ('Foreign language');
INSERT INTO category (name) values ('Geography');
INSERT INTO category (name) values ('History');
INSERT INTO category (name) values ('Law');
INSERT INTO category (name) values ('Linguistics');
INSERT INTO category (name) values ('Literature');
INSERT INTO category (name) values ('Mathematics');
INSERT INTO category (name) values ('Medical');
INSERT INTO category (name) values ('Music');
INSERT INTO category (name) values ('Philosophy');
INSERT INTO category (name) values ('Photography');
INSERT INTO category (name) values ('Physics');
INSERT INTO category (name) values ('Politics and society');
INSERT INTO category (name) values ('Psychology');
INSERT INTO category (name) values ('Religion');
INSERT INTO category (name) values ('Sociology');
INSERT INTO category (name) values ('Sport');
INSERT INTO category (name) values ('Travels');
INSERT INTO category (name) values ('Veterinary');
INSERT INTO category (name) values ('Zoological');
