# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle

image: gradle:alpine

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/read4share/.gradle

stages:
 - build
 - test
# - analyze

build:
  stage: build
  script:
    - cd read4share
    - gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - read4share/build
      - read4share/.gradle

test:
  stage: test
  script:
    - echo "Running tests"
    - cd read4share
    - gradle check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - read4share/build
      - read4share/.gradle

#sonarqube:
#  stage: analyze
#  script:
#    - echo "Running Sonarqube analysis"
#    - cd read4share-backend 
#    - gradle sonarqube -Dsonar.login="$SONAR_TOKEN"
#  allow_failure: true
#  only:
#    - main # analyze only the main branch
